<?php

/** @var \Tweakwise\Magento2Tweakwise\Block\Catalog\PersonalMerchandisingAnalytics $block */
/** @var  Escaper $escaper */

use Magento\Framework\Escaper;

/** @var \Tweakwise\Magento2Tweakwise\ViewModel\PersonalMerchandisingAnalytics $viewModel */
$viewModel = $block->getData('viewModel');
?>

<div x-data="{
    searchQuery: '<?= $escaper->escapeHtmlAttr($viewModel->getSearchQuery()); ?>',
    type: 'search'
}" x-init="() => {
    Tweakwise_Hyva_SearchPage({
        searchQuery: searchQuery,
        type: type
    }).init();
}">
</div>

<script src="<?= $escaper->escapeHtmlAttr($block->getViewFileUrl('Tweakwise_TweakwiseHyva::js/analytics.js')); ?>"></script>
