<?php

/** @var \Tweakwise\Magento2Tweakwise\Block\Catalog\PersonalMerchandisingAnalytics $block */
/** @var  Escaper $escaper */

use Magento\Framework\Escaper;

$searchQuery         = $block->getSearchQuery();
?>

<div x-data="{
    searchQuery: '<?= $escaper->escapeHtmlAttr($searchQuery); ?>'
}" x-init="() => {
    Tweakwise_Hyva_SearchPage({
        searchQuery: searchQuery
    }).init();
}">
</div>

<script src="<?= $escaper->escapeHtmlAttr($block->getViewFileUrl('Tweakwise_TweakwiseHyva::js/search-page.js')); ?>"></script>
