<?php

/** @var \Tweakwise\Magento2Tweakwise\Block\Catalog\PersonalMerchandisingAnalytics $block */
/** @var  Escaper $escaper */

use Magento\Framework\Escaper;

/** @var \Tweakwise\Magento2Tweakwise\ViewModel\PersonalMerchandisingAnalytics $viewModel */
$viewModel = $block->getData('viewModel');
?>

<div x-data="{
    productKey: '<?= $escaper->escapeHtmlAttr($viewModel->getProductKey()); ?>',
    type: 'product'
}" x-init="() => {
    // Initialize your JavaScript logic here
    Tweakwise_TweakwiseHyva_Pageview({
        productKey: productKey,
        type: type
    }).init();
}">
</div>

<script src="<?= $escaper->escapeHtmlAttr($block->getViewFileUrl('Tweakwise_TweakwiseHyva::js/analytics.js')); ?>"></script>
