<?php

/** @var \Tweakwise\Magento2Tweakwise\Block\Catalog\PersonalMerchandisingAnalytics $block */
/** @var  Escaper $escaper */

use Magento\Framework\Escaper;

$productKey          = $block->getProductKey();
?>

<div>TEEEEEEEEEEEST</div>

<div x-data="{
    productKey: '<?= $escaper->escapeHtmlAttr($productKey); ?>'
}" x-init="() => {
    // Initialize your JavaScript logic here
    Tweakwise_TweakwiseHyva_Pageview({
        productKey: productKey
    }).init();
}">
</div>

<script src="<?= $escaper->escapeHtmlAttr($block->getViewFileUrl('Tweakwise_TweakwiseHyva::js/product-page.js')); ?>"></script>
