<?php
/**
 * Tweakwise & Emico (https://www.tweakwise.com/ & https://www.emico.nl/) - All Rights Reserved
 *
 * @copyright Copyright (c) 2017-2022 Tweakwise.com B.V. (https://www.tweakwise.com)
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Tweakwise\Magento2Tweakwise\Block\LayeredNavigation\Navigation\State;

/** @var Escaper $escaper */
/** @var State $block */
?>
<?php /** @var Tweakwise\Magento2Tweakwise\Model\Catalog\Layer\Filter\Item[] $filters */ ?>
<?php $filters = $block->getActiveFilters() ?>
<?php if (!empty($filters)): ?>
    <div class="filter-current card my-4 pb-0"
         x-data="{ open: true }">
        <div class="filter-options-title flex justify-between items-center cursor-pointer hover:text-secondary-darker border-container pb-2"
             :class="{ 'border-b': open }"
             @click="open = !open">
            <strong><?= $escaper->escapeHtml(__('Now Shopping by')) ?></strong>
            <span class="py-1 px-1 rounded border border-container">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"
                 class="transition-transform transform duration-300 ease-in-out text-primary"
                 :class="open ? 'rotate-180' : ''">
                <path d="M19 9L12 16L5 9" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                      stroke-linejoin="round"/>
            </svg>
        </span>
        </div>
        <div class="items pt-1 py-3" x-show="open">
            <?php foreach ($filters as $filter): ?>
                <div class="item flex justify-between items-center mb-1">
                    <span>
                        <span class="filter-label block"><?= $escaper->escapeHtml(__($filter->getName())) ?></span>
                        <span class="filter-value text-sm block"><?= $escaper->escapeHtml($block->stripTags($filter->getLabel())) ?></span>
                    </span>
                    <?php $currentFilterName = $escaper->escapeHtmlAttr(__($filter->getName()) . " " . $block->stripTags($filter->getLabel())); ?>
                    <a class="action remove text-center block py-1.5 px-1.5 rounded border border-container text-primary hover:text-primary-darker"
                       href="<?= $escaper->escapeUrl($filter->getRemoveUrl()) ?>"
                       data-js-filter-id="<?= $escaper->escapeHtmlAttr($block->getActiveFilterCssId($filter)) ?>"
                       tabindex="0"
                       aria-label="<?= $escaper->escapeHtmlAttr(__('Remove') . " " . $currentFilterName) ?>"
                       role="button"
                       title="<?= $escaper->escapeHtmlAttr(__('Remove') . " " . $currentFilterName) ?>">
                        <svg class="fill-current" width="20" height="20" viewBox="0 0 20 20" fill="none"
                             xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" clip-rule="evenodd"
                                  d="M9 2C8.62123 2 8.27497 2.214 8.10557 2.55279L7.38197 4H4C3.44772 4 3 4.44772 3 5C3 5.55228 3.44772 6 4 6L4 16C4 17.1046 4.89543 18 6 18H14C15.1046 18 16 17.1046 16 16V6C16.5523 6 17 5.55228 17 5C17 4.44772 16.5523 4 16 4H12.618L11.8944 2.55279C11.725 2.214 11.3788 2 11 2H9ZM7 8C7 7.44772 7.44772 7 8 7C8.55228 7 9 7.44772 9 8V14C9 14.5523 8.55228 15 8 15C7.44772 15 7 14.5523 7 14V8ZM12 7C11.4477 7 11 7.44772 11 8V14C11 14.5523 11.4477 15 12 15C12.5523 15 13 14.5523 13 14V8C13 7.44772 12.5523 7 12 7Z"/>
                        </svg>
                    </a>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>
