<?php
/**
 * Tweakwise & Emico (https://www.tweakwise.com/ & https://www.emico.nl/) - All Rights Reserved
 *
 * @copyright Copyright (c) 2017-2022 Tweakwise.com B.V. (https://www.tweakwise.com)
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

declare(strict_types=1);

use Tweakwise\Magento2Tweakwise\Model\Catalog\Layer\Filter;
use Tweakwise\Magento2Tweakwise\Model\NavigationConfig;
use Magento\LayeredNavigation\Block\Navigation;

/** @var Navigation $block */
/** @var \Magento\Framework\Escaper $escaper */

if (!$block->canShowBlock()) {
    return;
}

/** @var $filters Filter[] */
$filters = $block->getFilters();

/** @var NavigationConfig $tweakwiseNavigationConfig */
$tweakwiseNavigationConfig = $block->getData('tweakwise_navigation_config');

$jsFormConfig = $tweakwiseNavigationConfig->getJsFormConfig();
$renderFilterButton = $tweakwiseNavigationConfig->isFormFilters();

$hasFilters = count($filters) > 0;
$filtered = count($block->getLayer()->getState()->getFilters());
?>

    <div class="block filter border border-container bg-container p-2 md:p-0 md:border-0 md:bg-transparent my-6<?=(!$hasFilters ? ' filter-no-options' : '')?>"
         x-data="initLayeredNavigation()"
         x-init="checkIsMobileResolution()"
         @resize.window.debounce="checkIsMobileResolution()"
         @visibilitychange.window.debounce="checkIsMobileResolution()"
    >
        <div class="block-title flex items-center justify-between md:p-0"
             @click="blockOpen = !blockOpen"
        >
            <span class="text-primary text-md text-xl md:text-2xl font-semibold uppercase"
                  data-count="<?= $escaper->escapeHtmlAttr($filtered)?>">
                <?= $escaper->escapeHtml(__('Shop By'))?>
            </span>
            <span class="py-1 px-1 bg-container-lighter rounded border border-container-darker hidden"
                  :class="{ 'block' : isMobile, 'hidden': !isMobile }">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none"
                     xmlns="http://www.w3.org/2000/svg"
                     class="transition-transform transform duration-300 ease-in-out text-primary"
                     :class="blockOpen ? 'rotate-180' : ''">
                    <path d="M19 9L12 16L5 9" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                          stroke-linejoin="round"/>
                </svg>
            </span>
        </div>

        <div class="block-content filter-content pt-2" x-show="isMobile && blockOpen || !isMobile">
            <form id="facet-filter-form"
                <?php if ($jsFormConfig): ?>
                    x-data="tweakwiseNavigationForm()"
                    x-init='initForm(<?= /* @noEscape */ $jsFormConfig ?>)'
                <?php endif; ?>
            >
                <?=$block->getChildHtml('state');?>

                <?php if ($block->getLayer()->getState()->getFilters()): ?>
                    <div class="block-actions filter-actions">
                        <a href="<?=$escaper->escapeUrl($block->getClearUrl())?>"
                           tabindex="0"
                           role="button"
                           class="action clear filter-clear text-xs text-primary underline hover:text-primary-darker"><span><?= $escaper->escapeHtml(__('Clear All'))?></span></a>
                    </div>
                <?php endif; ?>

                <?php if ($hasFilters): ?>
                    <div class="filter-options" id="narrow-by-list">
                        <?php foreach ($tweakwiseNavigationConfig->getFilterFormInput() as $name => $value): ?>
                            <?php //These are tweakwise system parameters which are needed for ajax navigation?>
                            <input type="hidden" name="<?= $escaper->escapeHtmlAttr($name)?>" value="<?= $escaper->escapeHtmlAttr($value)?>">
                        <?php endforeach; ?>

                        <?php foreach ($block->getFilters() as $filter): ?>
                            <?php if ($filter->getItemsCount()): ?>

                                <?php $filterActive = ($filter->isCollapsible()
                                    ? ($filter->isDefaultCollapsed() ? 'false' : 'true')
                                    : 'true'
                                ) ?>

                                <fieldset class="filter-option card my-4 pb-0 <?= $escaper->escapeHtmlAttr($filter->getCssClass())?>"
                                     x-data="{ open: <?= $escaper->escapeHtmlAttr($filterActive) ?>, showTooltip: false }">
                                    <legend id="<?= $escaper->escapeHtmlAttr($filter->getUrlKey()) ?>" class="sr-only"><?= $escaper->escapeHtml($filter->getName())?></legend>
                                    <div class="filter-options-title flex justify-between items-center border-container pb-2 <?= $escaper->escapeHtmlAttr($filter->isCollapsible()) ? 'cursor-pointer hover:text-secondary-darker' : '' ?>"
                                         :class="{ 'border-b': open }"
                                         <?= $filter->isCollapsible() ? '@click="open = !open"' : ''?>>
                                        <span class="title flex text-md md:text-lg font-semibold">
                                            <?= $escaper->escapeHtml(__($filter->getName()))?>

                                            <?php $tooltip = $filter->getTooltip(); ?>
                                            <?php if ($tooltip): ?>
                                                <span class="ml-2 mt-1 block relative tooltip">
                                                    <span @mouseover="showTooltip = true"
                                                          @mouseleave="showTooltip = false"
                                                          tabindex="0"
                                                          aria-label="<?= $escaper->escapeHtmlAttr(__('More info')) ?>"
                                                          aria-describedby="<?= $escaper->escapeHtmlAttr($filter->getUrlKey()) ?>-tooltip"
                                                          class="flex justify-center items-center relative text-blue-900 w-5 h-5 cursor-pointer tooltip-toggle">
                                                        <svg xmlns="http://www.w3.org/2000/svg"
                                                             viewBox="0 0 18 18" fill="currentColor">
                                                          <path fill-rule="evenodd"
                                                                d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z"
                                                                clip-rule="evenodd"/>
                                                        </svg>
                                                    </span>
                                                    <span x-cloak
                                                          x-show.transition.origin.top="showTooltip"
                                                            id="<?= $escaper->escapeHtmlAttr($filter->getUrlKey()) ?>-tooltip"
                                                          class="absolute bottom-0 mb-8 block bg-gray-900 bg-opacity-95 rounded p-2 text-white text-xs font-normal absolute w-32 z-10 text-left tooltip-content"><?= $escaper->escapeHtml($tooltip)?></span>
                                                </span>
                                            <?php endif; ?>
                                        </span>

                                        <?php if ($filter->isCollapsible()): ?>
                                            <span
                                                class="py-1 px-1 rounded border border-container"
                                                :tabindex="!open ? '0' : '-1'"
                                                role="button"
                                                @keydown.enter.prevent="open = !open"
                                                aria-label="<?= $escaper->escapeHtmlAttr(__('Expand filter options for %1', $filter->getName())) ?>"
                                            >
                                                <svg width="24" height="24" viewBox="0 0 24 24" fill="none"
                                                    xmlns="http://www.w3.org/2000/svg"
                                                    class="transition-transform transform duration-300 ease-in-out text-primary"
                                                    :class="open ? 'rotate-180' : ''">
                                                    <path d="M19 9L12 16L5 9" stroke="currentColor" stroke-width="2"
                                                        stroke-linecap="round"
                                                        stroke-linejoin="round"/>
                                                </svg>
                                            </span>
                                        <?php endif; ?>
                                    </div>
                                    <div class="filter-options-content py-3 hidden"
                                         :class="{ '!block': open, 'hidden': !open }"
                                    >
                                        <?=/* @noEscape */
                                        $block->getChildBlock('renderer')->render($filter)?>
                                    </div>
                                </fieldset>

                                <?php if ($renderFilterButton): ?>
                                    <div class="show-items-link">
                                        <button type="button"
                                                class="btn btn-primary btn-block js-btn-filter"
                                                aria-label="<?= $escaper->escapeHtmlAttr(__('Apply filters')) ?>"
                                        >
                                            <?= $escaper->escapeHtml(__('Show items')); ?>

                                        </button>
                                    </div>
                                <?php endif; ?>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>

                <?= $block->getChildHtml('loading')?>
            </form>
        </div>
    </div>

    <script>
        'use strict';

        function initLayeredNavigation() {
            return {
                isMobile: false,
                blockOpen: false,
                checkIsMobileResolution() {
                    this.isMobile = window.outerWidth < 768
                }
            }
        }

        /**
         * Sort items based on alternate sort (if available)
         */

        function initTweakwiseNavigationItems() {
            return {
                moreItemsShow: false,
                sortItems(hasAlternateSort) {
                    if (!hasAlternateSort || !this.$refs.items || !this.$refs.items.children) {
                        return
                    }

                    const items = this.$refs.items
                    const sortType = this.moreItemsShow ? 'alternateSort' : 'originalSort'

                    Array.from(items.children)
                        .sort((a, b) => a.dataset[sortType].localeCompare(b.dataset[sortType],undefined,{numeric: true}))
                        .forEach((item) => {
                            items.appendChild(item);
                            item.focus();
                        });
                },
                toggleShowMore(moreItemsShow, hasAlternateSort) {
                    this.moreItemsShow = moreItemsShow
                    this.sortItems(hasAlternateSort)

                    // Focus the first visible item
                    this.$nextTick(() => {
                        const items = this.$refs.items;
                        if (!items) return;
                        const firstVisible = Array.from(items.children).find(
                            item => item.style.display !== 'none'
                        );

                        if (firstVisible) {
                            // Try to focus input or anchor
                            const input = firstVisible.querySelector('input, a, button');
                            if (input) input.focus();
                        }
                    });
                }
            }
        }

        function initFilterSearch() {
            return {
                filterSearch() {
                    let items = this.$refs.items;
                    const filterSearch = this.$refs.tw_filtersearch;
                    let value = filterSearch.value.toLowerCase().trim();
                    let noItems = this.$refs.search_no_results;
                    let moreItems = this.$refs.moreItems;
                    let lessItems = this.$refs.lessItems;
                    let self = this;

                    //swatch
                    if (!items || !items.children) {
                        items = this.$refs.swatch;
                    }

                    if (!items || !items.children) {
                        return;
                    }

                    Array.from(items.children).forEach(function(item) {
                        //find input element in item
                        let input = item.querySelector('input');
                        if (value.length === 0) {
                            // Reset to initial state
                            item.style.display = '';
                        } else if (self.asciiFold(input.value).indexOf(self.asciiFold(value)) === -1) {
                            item.style.display = 'none';
                        } else {
                            item.style.display = 'block';
                        }
                    });

                    let visibleItems = Array.from(items.children).filter(item => item.style.display !== 'none');
                    if(visibleItems.length < 1) {
                        noItems.style.display = '';
                    } else {
                        noItems.style.display = 'none';
                    }

                    if (moreItems) {
                        if(value.length === 0) {
                            moreItems.style.display = '';
                            lessItems.style.display = '';

                        } else {
                            moreItems.style.display = 'none';
                            lessItems.style.display = 'none';
                        }
                    }
                },
                asciiFold(value) {
                    const SPECIAL_MAP = {
                        'ß': 'ss', 'Æ': 'AE', 'æ': 'ae', 'Ø': 'O', 'ø': 'o', 'Œ': 'OE', 'œ': 'oe',
                        'Þ': 'Th', 'þ': 'th', 'Đ': 'D', 'đ': 'd', 'Ł': 'L', 'ł': 'l', 'Ħ': 'H', 'ħ': 'h'
                    };
                    const SPECIAL_REGEX = new RegExp(Object.keys(SPECIAL_MAP).join('|'), 'g');
                    if (typeof value.normalize === 'function') {
                        return value.normalize('NFKD')
                            .replace(/\p{M}/gu, '')
                            .replace(SPECIAL_REGEX, ch => SPECIAL_MAP[ch])
                            .normalize('NFC')
                            .toLowerCase()
                            .trim();
                    }
                    // Fallback: just replace special chars and lowercase
                    return value.replace(SPECIAL_REGEX, ch => SPECIAL_MAP[ch])
                        .toLowerCase()
                        .trim();
                }
            }
        }
    </script>

<?=$block->getChildHtml('tweakwise.navigation.form');?>
<?=$block->getChildHtml('tweakwise.navigation.slider');?>
