<?php
/**
 * Tweakwise & Emico (https://www.tweakwise.com/ & https://www.emico.nl/) - All Rights Reserved
 *
 * @copyright Copyright (c) 2017-2022 Tweakwise.com B.V. (https://www.tweakwise.com)
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Tweakwise\Magento2Tweakwise\Block\LayeredNavigation\RenderLayered\LinkRenderer\ItemRenderer;

/** @var Escaper $escaper */
/** @var ItemRenderer $block */

$item = $block->getItem();
$hasHiddenItems = $block->hasHiddenItems();
$hasAlternateSortOrder = $block->hasAlternateSortOrder();

?>

<li class="item"
    :class="{ 'block': moreItemsShow, 'hidden': '<?=$block->itemDefaultHidden($item)?>' && !moreItemsShow }"
    <?php if ($hasAlternateSortOrder): ?>
        data-alternate-sort="<?= $item->getAlternateSortOrder(); ?>"
        data-original-sort="<?= $index; ?>"
    <?php endif; ?>
>
    <a href="<?= $block->getCategoryUrl($item) ?>" class="flex w-full py-1 mb-1 hover:text-black">
        <?= $block->getItemPrefix() ?>
        <?= $escaper->escapeHtml($item->getLabel()) ?>
        <?= $block->getItemPostfix() ?>

        <?php if ($block->shouldDisplayProductCountOnLayer()): ?>
            <span class="count block text-primary ml-auto">
                (<?= htmlentities((string)$item->getCount()) ?>)
            </span>
        <?php endif; ?>
    </a>

    <?php if ($block->hasChildren()): ?>
        <ol class="items child-items">
            <?php foreach ($block->getChildren() as $child): ?>
                <?= $block->renderLinkItem($child) ?>
            <?php endforeach; ?>
        </ol>
    <?php endif; ?>
</li>
