<?php
/** @var \Emico\AttributeLanding\Block\OverviewPage\View $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<div><?= /* @noEscape */ $block->getContentFirst()?></div>
<div class="landingpages-grid grid sm:grid-cols-2 md:grid-cols-4 lg:grid-cols-4">
    <?php foreach ($block->getLandingPages() as $landingPage): ?>
        <div class="m-2">
            <a href="<?= $escaper->escapeUrl($landingPage->getUrlPath()) ?>"><?= $escaper->escapeHtml($landingPage->getHeading() ?: $landingPage->getName()) ?>
                <img src="<?= $escaper->escapeHtmlAttr($block->getLandingPageImage($landingPage))?>" />
            </a>
        </div>
    <?php endforeach; ?>
</div>
<div><?= /* @noEscape */ $block->getContentLast()?></div>
