<?php

/** @var \Tweakwise\Magento2Tweakwise\Block\Catalog\PersonalMerchandisingAnalytics $block */
/** @var  Escaper $escaper */

use Magento\Framework\Escaper;

/** @var \Tweakwise\Magento2Tweakwise\ViewModel\PersonalMerchandisingAnalytics $viewModel */
$viewModel = $block->getData('viewModel');
$analyticsType = $block->getData('analyticsType');
$value = $analyticsType === $viewModel->getValue($analyticsType);
?>

<div x-data="{
    value: '<?= $escaper->escapeHtmlAttr($value); ?>',
    type: '<?= $escaper->escapeHtmlAttr($analyticsType); ?>'
}" x-init="() => {
    Tweakwise_Hyva_Analytics({
        value: value,
        type: type
    }).init();
}">
</div>

<script src="<?= $escaper->escapeHtmlAttr($block->getViewFileUrl('Tweakwise_TweakwiseHyva::js/analytics.js')); ?>"></script>
