<?php

/** @var \Tweakwise\Magento2Tweakwise\Block\Catalog\PersonalMerchandisingAnalytics $block */
/** @var  Escaper $escaper */

use Magento\Framework\Escaper;
use Tweakwise\Magento2Tweakwise\Model\NavigationConfig;

/** @var \Tweakwise\Magento2Tweakwise\ViewModel\PersonalMerchandisingAnalytics $viewModel */
$viewModel = $block->getData('viewModel');

/** @var NavigationConfig $tweakwiseNavigationConfig */
$tweakwiseNavigationConfig = $block->getData('tweakwise_navigation_config');
$jsFormConfig = $tweakwiseNavigationConfig ? json_decode($tweakwiseNavigationConfig->getJsFormConfig()) : [];
$twRequestId = $jsFormConfig->tweakwiseNavigationForm->twRequestId ?? '';

$analyticsTypes = $block->getData('analyticsTypes');
$eventsData = $viewModel->getEventsData($analyticsTypes, $twRequestId);
?>

<div x-data='{
    eventsData: <?= $eventsData ?>,
    bindItemClickEventsConfig: {
        productListSelector: ".products.wrapper",
        productSelector: ".product-item",
        analyticsEndpoint: "<?= /* @noEscape */ $jsFormConfig->tweakwiseNavigationForm->analyticsEndpoint ?? ''; ?>",
        twRequestId: "<?= $escaper->escapeHtmlAttr($twRequestId); ?>"
    }
}' x-init='() => {
    Tweakwise_Hyva_Analytics({
        eventsData: eventsData,
        bindItemClickEventsConfig: bindItemClickEventsConfig
    }).init();
}'>
</div>

<script src="<?= $escaper->escapeHtmlAttr($block->getViewFileUrl('Tweakwise_TweakwiseHyva::js/analytics.js')); ?>"></script>
