<?php

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Tweakwise\Magento2Tweakwise\Model\NavigationConfig;

/** @var Template $block */
/** @var Escaper $escaper */

/** @var \Tweakwise\Magento2Tweakwise\ViewModel\PersonalMerchandisingAnalytics $viewModel */
$viewModel = $block->getData('viewModel');

/** @var NavigationConfig $tweakwiseNavigationConfig */
$tweakwiseNavigationConfig = $block->getData('tweakwise_navigation_config');
$jsFormConfig = $tweakwiseNavigationConfig ? json_decode($tweakwiseNavigationConfig->getJsFormConfig()) : [];
$twRequestId = $jsFormConfig->tweakwiseNavigationForm->twRequestId ?? '';

$eventsData = $viewModel->getEventsData($twRequestId);
?>

<div x-data='{
    eventsData: <?= $eventsData ?>,
    bindItemClickEventsConfig: {
        productListSelector: ".products.wrapper",
        productSelector: ".product-item",
        productItemInfoPrefix: "<?= $escaper->escapeHtmlAttr($jsFormConfig->tweakwiseNavigationForm->productSelector ?? 'product-item-info'); ?>",
        twRequestId: "<?= $escaper->escapeHtmlAttr($twRequestId); ?>",
        storeId: <?= (int)$viewModel->getStoreManager()->getStore()->getId(); ?>
    }
}' x-init='() => {
    Tweakwise_Hyva_Analytics({
        eventsData: eventsData,
        bindItemClickEventsConfig: bindItemClickEventsConfig
    }).init();
}'>
</div>

<script src="<?= $escaper->escapeHtmlAttr($block->getViewFileUrl('Tweakwise_TweakwiseHyva::js/analytics.js')); ?>"></script>
