<?php
/**
 * Tweakwise & Emico (https://www.tweakwise.com/ & https://www.emico.nl/) - All Rights Reserved
 *
 * @copyright Copyright (c) 2017-2022 Tweakwise.com B.V. (https://www.tweakwise.com)
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Emico\Tweakwise\Block\LayeredNavigation\RenderLayered\TreeRenderer\ItemRenderer;

/** @var Escaper $escaper */
/** @var ItemRenderer $block */

$item = $block->getItem();

?>
<li class="item">
    <a href="<?= $escaper->escapeUrl($item->getUrl()) ?>" class="flex w-full py-1 mb-1 hover:text-black">
        <?= $block->getItemPrefix() ?>
        <?= $escaper->escapeHtml($item->getLabel()) ?>
        <?= $block->getItemPostfix() ?>

        <?php if ($block->shouldDisplayProductCountOnLayer()): ?>
            <span class="count block text-primary ml-auto">
                (<?= htmlentities((string)$item->getCount()) ?>)
            </span>
        <?php endif; ?>
    </a>

    <?php if ($block->hasChildren()): ?>
        <ol class="items child-items">
            <?php foreach ($item->getChildren() as $child): ?>
                <?= $block->renderTreeItem($child) ?>
            <?php endforeach; ?>
        </ol>
    <?php endif; ?>
</li>
