<?php
/**
 * Tweakwise & Emico (https://www.tweakwise.com/ & https://www.emico.nl/) - All Rights Reserved
 *
 * @copyright Copyright (c) 2017-2022 Tweakwise.com B.V. (https://www.tweakwise.com)
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

declare(strict_types=1);

use Magento\Framework\Escaper;
use Tweakwise\Magento2Tweakwise\Block\LayeredNavigation\RenderLayered\DefaultRenderer;

/** @var Escaper $escaper */
/** @var DefaultRenderer $block */

$hasHiddenItems = $block->hasHiddenItems();
$hasAlternateSortOrder = $block->hasAlternateSortOrder();

?>
<div x-data="initTweakwiseNavigationItems()" x-init='sortItems(<?= (int)$hasAlternateSortOrder ?>)'>
    <?php if ($block->isSearchable()): ?>
        <input aria-hidden="true" tabindex="-1" @keyUp="filterSearch()" x-ref="tw_filtersearch" x-data="initFilterSearch()" data-max-visible="<?= $escaper->escapeHtmlAttr($block->getMaxItemsShown())?>" type="text" class="tw_filtersearch js-skip-submit" name="tw_filtersearch" placeholder="<?= $escaper->escapeHtmlAttr($block->getSearchPlaceholder()); ?>" >
        <div x-ref="search_no_results" style="display: none" class="search_no_results empty"><?= $escaper->escapeHtml($block->getSearchNoResultsText()); ?></div>
    <?php endif; ?>
    <ol class="items" x-ref="items">
        <?php foreach ($block->getItems() as $index => $item): ?>
            <li class="item"
                :class="{ 'block': moreItemsShow, 'hidden': '<?= $escaper->escapeHtmlAttr($block->itemDefaultHidden($item))?>' && !moreItemsShow }"
                <?php if ($hasAlternateSortOrder): ?>
                    data-alternate-sort="<?= $escaper->escapeHtmlAttr($item->getAlternateSortOrder()); ?>"

                    data-original-sort="<?= $escaper->escapeHtmlAttr($index); ?>"
                <?php endif; ?>
            >
                <a aria-hidden="true" tabindex="-1" <?= /* @noEscape */ $block->renderAnchorHtmlTagAttributes($item); ?> class="flex w-full py-1 mb-1 hover:text-black">
                    <?php $cssId = $item->getCssId(); ?>
                    <?php if ($block->showCheckbox()): ?>
                        <label for="<?= $escaper->escapeHtmlAttr($cssId) ?>" class="block m-0 font-normal flex w-full">
                            <input id="<?= $escaper->escapeHtmlAttr($cssId) ?>"
                                   name="<?= $escaper->escapeHtmlAttr($item->getFilter()->getUrlKey()) ?>[]"
                                   type="checkbox" <?= ($item->isSelected() ? 'checked="checked"' : '') ?>
                                   value="<?= $escaper->escapeHtmlAttr($item->getLabel()) ?>"
                                   class="block w-4 h-4 mr-2 mt-1"
                                   tabindex="0"
                                   aria-labelledby="<?= $escaper->escapeHtmlAttr($item->getFilter()->getUrlKey()) ?> <?= $escaper->escapeHtmlAttr($cssId) ?>"
                            >

                            <?= $escaper->escapeHtml($block->getItemPrefix()) ?>
                            <?= $escaper->escapeHtml($item->getLabel()) ?>
                            <?= $escaper->escapeHtml($block->getItemPostfix()) ?>

                            <?php if ($block->shouldDisplayProductCountOnLayer()): ?>
                                <span class="count block text-primary ml-auto">
                                    (<?= $escaper->escapeHtml($item->getCount()) ?>)
                                </span>
                            <?php endif; ?>
                        </label>
                    <?php else: ?>
                        <?= $escaper->escapeHtml($block->getItemPrefix()) ?>
                        <?= $escaper->escapeHtml($item->getLabel()) ?>
                        <?= $escaper->escapeHtml($block->getItemPostfix()) ?>

                        <?php if ($block->shouldDisplayProductCountOnLayer()): ?>
                            <span class="count block text-primary ml-auto">(<?= $escaper->escapeHtml($item->getCount()) ?>)</span>
                        <?php endif; ?>
                    <?php endif; ?>
                </a>
            </li>
        <?php endforeach; ?>
    </ol>

    <?php if ($hasHiddenItems): ?>
        <a href="#" class="more-items underline cursor-pointer"
           @click.prevent="toggleShowMore(true, <?= (int)$hasAlternateSortOrder ?>)"
           :class="{ 'hidden': moreItemsShow }"
           x-ref="moreItems"
           role="button"
           tabindex="0"
        ><?= $escaper->escapeHtml(__($block->getMoreItemText())) ?></a>
        <a href="#" class="less-items underline cursor-pointer"
           x-cloak
           @click.prevent="toggleShowMore(false, <?= (int)$hasAlternateSortOrder ?>)"
           :class="{ 'block': moreItemsShow, 'hidden': !moreItemsShow }"
           x-ref="lessItems"
           role="button"
           tabindex="0"
        ><?= $escaper->escapeHtml(__($block->getLessItemText())) ?></a>
    <?php endif; ?>
</div>
