<?php
/**
 * Tweakwise & Emico (https://www.tweakwise.com/ & https://www.emico.nl/) - All Rights Reserved
 *
 * @copyright Copyright (c) 2017-2022 Tweakwise.com B.V. (https://www.tweakwise.com)
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

declare(strict_types=1);

use Tweakwise\Magento2Tweakwise\Block\LayeredNavigation\RenderLayered\LinkRenderer;

/** @var LinkRenderer $block */
/** @var \Magento\Framework\Escaper $escaper */
$hasHiddenItems = $block->hasHiddenItems();
$hasAlternateSortOrder = $block->hasAlternateSortOrder();
?>
<div x-data="initTweakwiseNavigationItems()" x-init='sortItems(<?= (int)$hasAlternateSortOrder ?>)'>
    <ol class="items" x-ref="items">
        <?php foreach ($block->getItems() as $item): ?>
            <?= /* @noEscape */ $block->renderLinkItem($item) ?>
        <?php endforeach; ?>
    </ol>

    <?php if ($hasHiddenItems): ?>
        <a href="#" class="more-items underline cursor-pointer"
           @click.prevent="toggleShowMore(true, <?= (int)$hasAlternateSortOrder ?>)"
           :class="{ 'hidden': moreItemsShow }"
           tabindex="0"
           role="button"
        ><?= $escaper->escapeHtml(__($block->getMoreItemText())) ?></a>
        <a href="#" class="less-items underline cursor-pointer"
           x-cloak
           @click.prevent="toggleShowMore(false, <?= (int)$hasAlternateSortOrder ?>)"
           :class="{ 'block': moreItemsShow, 'hidden': !moreItemsShow }"
           tabindex="0"
           role="button"
        ><?= $escaper->escapeHtml(__($block->getLessItemText())) ?></a>
    <?php endif; ?>
</div>
