<?php
/**
 * Tweakwise & Emico (https://www.tweakwise.com/ & https://www.emico.nl/) - All Rights Reserved
 *
 * @copyright Copyright (c) 2017-2022 Tweakwise.com B.V. (https://www.tweakwise.com)
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

declare(strict_types = 1);

use Emico\Tweakwise\Block\LayeredNavigation\RenderLayered\SwatchRenderer;
use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;

/** @var SwatchRenderer $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */


// TODO: Remove when getItems is added to SwatchRenderer
return;
?>
<div class="swatch-attribute swatch-layered">
    <div class="swatch-attribute-options clearfix flex flex-wrap">
        <?php foreach ($block->getItems() as $index => $item): ?>
            <a <?= $block->renderAnchorHtmlTagAttributes($item); ?>
                    aria-label="<?= $escaper->escapeHtml($item->getLabel()) ?>"
                    class="swatch-option-link-layered swatch-option cursor-pointer select-none mr-2"
            >
                <?php $cssId = $item->getCssId(); ?>
                <input id="<?= $cssId ?>" style="display: none"
                       name="<?= $item->getFilter()->getFacet()->getFacetSettings()->getUrlKey() ?>[]"
                       type="checkbox" <?= ($item->isSelected() ? 'checked="checked"' : '') ?>
                       value="<?= $escaper->escapeHtmlAttr($item->getLabel()) ?>"
                >
                <label for="<?= $cssId ?>"
                       class="swatch-option-link-layered swatch-option cursor-pointer relative select-none border-container-darker w-8 h-8 rounded-full swatch-color swatch-color-<?= strtolower($escaper->escapeHtml($item->getLabel())) ?><?= ($item->isSelected() ? ' active' : '') ?>"
                >
                    <span class="hidden">
                        <?= $escaper->escapeHtml($item->getLabel()) ?>
                    </span>
                </label>
            </a>
        <?php endforeach; ?>
    </div>
</div>