<?php
/** @var array $banners  */
$banners = $block->getData('banners');
$styling = !empty($banners[0]) && $banners[0]['location'] == 'ContainerTop' ? 'style="margin-right: auto; margin-left: auto; padding-left: 1.5rem; padding-right: 1.5rem;"' : '';
?>
<div class="searchbanners" <?= $styling ?>>
    <?php foreach ($banners as $banner) : ?>
        <?php if (!empty($banner['clickurl'])): ?>
            <a href="<?=$banner['clickurl'];?>" type=<?=$banner['clicktarget'];?>">
        <?php endif; ?>
                <img class="searchbanner <?=strtolower($banner['type']);?>" src="<?=$banner['imageurl'] ?>">
        <?php if (!empty($banner['clickurl'])): ?>
            </a>
        <?php endif; ?>
    <?php endforeach; ?>
</div>

<style>
    .mobile {
        display: none;
    }

    .searchbanners {
        max-width: 1536px;
    }

    .searchbanner {
        width: 100%;
    }

    .toolbar {
        margin-bottom: 1.875rem;
    }

    @media only screen and (max-width: 768px) {
        .searchbanner.desktop {
            display: none;
        }

        .searchbanner.mobile {
            display: block;
        }
    }
</style>
