<?php

use Magento\Catalog\Block\Product\AbstractProduct;
use Magento\Framework\Escaper;
use Tweakwise\Magento2Tweakwise\Model\Visual;

/**
 * @var AbstractProduct $block
 * @var Escaper $escaper
 */

/** @var Visual $visual */
$visual = $block->getData('visual');
if (!$visual) {
    return;
}
$hasUrl = !empty($visual->getUrl());
$visualTrackingId = (string)$visual->getData('tw_id');
?>

<?php if ($hasUrl): ?>
<a href="<?= $escaper->escapeUrl($visual->getUrl()); ?>">
    <?php endif; ?>
    <div
        class="product-item visual"
        id="<?= $escaper->escapeHtmlAttr((string)$visual->getId()) ?>"
        data-product-id="<?= $escaper->escapeHtmlAttr($visualTrackingId) ?>"
        data-product-id-type="tweakwise"
    >
        <img class="visual-image" src="<?= $escaper->escapeUrl($visual->getImageUrl()) ?>" loading="lazy" alt="<?= $escaper->escapeHtmlAttr($visual->getName()) ?>"/>
    </div>
    <?php if ($hasUrl): ?>
</a>
<?php endif; ?>
